spring.application.name=gestao-frota

spring.datasource.url=jdbc:mysql://localhost:3306/gestao_frota
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true